app: serverless-typesctript-starter
service: ${self:app}
frameworkVersion: '3'
useDotenv: true

package:
  individually: true

provider:
  name: aws
  stage: ${opt:stage, 'staging'}
  region: us-east-1
  timeout: 29
  profile: default
  runtime: nodejs18.x
  # iam:
  #   role:
  #     statements:
  #       - Effect: Allow
  #         Action:
  #           - ses:SendEmail
  #           - ses:SendRawEmail
  #         Resource: '*'
  # vpc:
  #   securityGroupIds:
  #     - ${env:AWS_SECURITY_GROUP_ID, ''}
  #   subnetIds:
  #     - ${env:AWS_SUBNET_ID_1, ''}
  #     - ${env:AWS_SUBNET_ID_2, ''}
  #     - ${env:AWS_SUBNET_ID_3, ''}
  #     - ${env:AWS_SUBNET_ID_4, ''}

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  esbuild:
    target: node18

functions:
  hello:
    handler: handlers/hello.handler
    # environment:
    #   MONGODB_URI: ${env:MONGODB_URI}
    events:
      - httpApi:
          path: /hello
          method: get
          # authorizer:
          #   type: aws_iam
